const QUIZ_FULL_MARKS_REWARD_COEFFICIENT = 50;
const QUIZ_CORRECT_QUESTION_REWARD_COEFFICIENT = 10;
const DISTANCE_COEFFECIENT = 0.1;
const ELEVATION_GAIN_COEFFECIENT = 1;
const NEW_BIRD_REWARD_COEFFECIENT = 1000;
const REPEAT_BIRD_REWARD_COEFFECIENT = 100;
const EXERCISE_GOAL_COEFFECIENT = 300;
const BIRD_GOAL_COEFFECIENT = 50;
const BIRD_FLOW_DURATION = 10; //in minutes
const BRONZE_CHALLANGE = 1000;
const SILVER_CHALLANGE = 10000;
const GOLD_CHALLANGE = 30000;

const RARITY_1_PROB = 50;
const RARITY_2_PROB = 20;
const RARITY_3_PROB = 15;
const RARITY_4_PROB = 10;
const RARITY_5_PROB = 3;
const RARITY_6_PROB = 2;

const FITNESS_ASSESSMENT_TIME = 15; //in minutes

module.exports = {
    QUIZ_FULL_MARKS_REWARD_COEFFICIENT,
    QUIZ_CORRECT_QUESTION_REWARD_COEFFICIENT,
    DISTANCE_COEFFECIENT,
    ELEVATION_GAIN_COEFFECIENT,
    NEW_BIRD_REWARD_COEFFECIENT,
    REPEAT_BIRD_REWARD_COEFFECIENT,
    EXERCISE_GOAL_COEFFECIENT,
    BIRD_GOAL_COEFFECIENT,
    BIRD_FLOW_DURATION,
    BRONZE_CHALLANGE,
    SILVER_CHALLANGE,
    GOLD_CHALLANGE,
    RARITY_1_PROB,
    RARITY_2_PROB,
    RARITY_3_PROB,
    RARITY_4_PROB,
    RARITY_5_PROB,
    RARITY_6_PROB,
    FITNESS_ASSESSMENT_TIME
};